# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xiaomi_Models',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('level', models.IntegerField(default=0)),
                ('now', models.DateTimeField(auto_now_add=True)),
                ('comm', models.CharField(default='\u9996\u7248\u5757', max_length=20)),
            ],
        ),
    ]
